### ISSUE TITLE
我想请问一个问题  可能和这个 相关性不太大

### ISSUE THREAD

**Issue by zZ-GitHub** [zouzg/mybatis-generator-gui#108]
### 我是一个初学着 

------------
我使用
### gradle
构建
ssm项目 使用了mybatis 的代码生成器
 不知道是不是我配置的问题
在我编译代码的时候  使用@Resource  

 会报出异常   could  not autowire no beans of 'XXXMapper' type found 
但是其实不影响运行使用
有人说使用 @Autowired(required = false)    是解决了这个报错   有没有什么其他方法 

诸如 修改配置的

**Comment by VincentHD** [comment]
这个错误是因为接口实现类里面缺少@Service注解。

**Comment by zZ-GitHub** [comment]
我想我可能没有描述清楚  我是在 service  自动注入   某一mapper 的时候  的问题  不是 注入  service 的问题

**Comment by zouzg** [comment]
你需要配置mybatis扫描mapper文件的配置，如果是Spring 3.0以上版本，可以使用Java配置，例如下图：
![image](https://user-images.githubusercontent.com/3505708/30043790-38be3f90-922c-11e7-8ec6-9425f7e328de.png)
具体方法请google一下
