### ISSUE TITLE
可否加入批量插入的功能？

### ISSUE THREAD

**Issue by arraysnow** [zouzg/mybatis-generator-gui#117]

**Comment by arraysnow** [comment]
工作中总是涉及到批量插入、批量更新这样的情况，mybatis-generator又缺少像样的插件
这是国人开发的一个插件，但是好久不维护了https://github.com/itfsw/mybatis-generator-plugin

我感觉这个功能挺重要的，希望作者可以多多关注

**Comment by zouzg** [comment]
谢谢分享，可以考虑一下，其中一些插件看起来不错。
