### ISSUE TITLE
能否添加生成注解版本的而不是xml版的

### ISSUE THREAD

**Issue by mustang2247** [zouzg/mybatis-generator-gui#128]
能否添加生成注解版本的而不是xml版的
如下：
@Select("select * from versioncontrol where id = #{id}")
    VersionConfig findVersionInfoById(@Param("id") int id);

**Comment by kmanzxbin** [comment]
+1

**Comment by willlau0524** [comment]
注解版本在做字段映射的时候不好做，每一个注解都要加上映射，而xml文件只需要写一次即可，直接使用 resultMap=xxx 即可

**Comment by zouzg** [comment]
注解版本使用起来不是很灵活，使用场景有限，还是建议使用XML的方式。
