### ISSUE TITLE
安装有JDK9的环境下启动报错

### ISSUE THREAD

**Issue by Mandarava** [zouzg/mybatis-generator-gui#130]
![qq 20171112110300](https://user-images.githubusercontent.com/8132343/32695508-34a58e84-c799-11e7-8d37-6f169226b42b.jpg)
![qq 20171112110229](https://user-images.githubusercontent.com/8132343/32695510-37130444-c799-11e7-921b-9e9e585a98a0.jpg)

**Comment by zouzg** [comment]
JDK 9目前还不支持，谢谢。我之前安装过jdk9，运行其他项目都各种问题，所以目前暂时等稳定了之后再支持吧。
