### ISSUE TITLE
编码问题，急！急！急！

### ISSUE THREAD

**Issue by wangxiangyun** [zouzg/mybatis-generator-gui#132]
生成的java代码默认是gbk的。 copy到idea中 乱码？ 更改编码方式 解析出错！所以希望生成的时候用UTF-8来生成。谢谢，看了你的源码 ，时间短没有看到你怎么写到磁盘的不然我自己改了！谢谢楼主咯

**Comment by zouzg** [comment]
麻烦提供一下你的环境信息，越详细越好。包括不限于java版本，操作系统版本，你目前的语言设置（Windows的语言设置里面），乱码截图等。

**Comment by amoxu** [comment]
-notepad++可以转换文件编码

**Comment by xander-personal** [comment]
已提交针对这个问题的pull request

![image](https://user-images.githubusercontent.com/11306208/33468260-fb61c208-d695-11e7-92ee-aeb2947f8d39.png)

**Comment by zouzg** [comment]
@xander-personal 感谢贡献，已经merge了
