### ISSUE TITLE
可不可以增加通用的select，update，insert

### ISSUE THREAD

**Issue by jszmt** [zouzg/mybatis-generator-gui#136]
我觉得生成出来的文件不一定是越多越好，反而是越精华越简练越好。
所谓的通用的select就是查询全字段，然后条件也是全字段例如：
  SELECT * FROM table_name  WHERE  1=1
         《 if test="id!= null"  》
             and id= #{id,jdbcType=VARCHAR} 
         《/if》
         《if test="name!= null" 》
             and name= #{name,jdbcType=VARCHAR} 
         《/if》 
其实一个基础的xml映射，有两个通用的select（一个返回list，一个limit 1 返回具体domain），再有一个通用的update和insert 就完全可以了，希望作者可以考虑一下

**Comment by javaxiaoyetan** [comment]
我也觉得，工具还是很好的，就是为什么会多出来那么多example的代码？其实没啥实用性，还得自己手动去删除

**Comment by zouzg** [comment]
不建设使用select *，可以参考如下文章：
http://www.cnblogs.com/huangsheng/p/6857503.html
