### ISSUE TITLE
openjdk缺少 javafx 相关的包怎么解决

### ISSUE THREAD

**Issue by JokingLove** [zouzg/mybatis-generator-gui#143]
这些包在maven 仓库中有吗，我找了一下，出来了一些，但是我不知道具体导入哪一个

**Comment by zouzg** [comment]
请使用Oracle JDK

**Comment by JokingLove** [comment]
@zouzg  嗯，我使用的是  oracle JDK，linux版， 难道是Linux版的少这部分了吗

**Comment by zouzg** [comment]
是的, Linux版是少这部分的，Mac与Windows都是OK的。

**Comment by JokingLove** [comment]
嗯，感谢大神，工具还是很好用的

**Comment by zzl93** [comment]
使用maven导入javafx-fxml可以解决
```
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-fxml</artifactId>
    <version>11</version>
</dependency>
```

**Comment by tankilo** [comment]
> 请使用Oracle JDK

微信号回复的GUI 发现百度网盘失效了。 我使用Oracle OpenJDK无法本地编译，Oracle JDK是在哪里下载了。难受
