### ISSUE TITLE
希望可以有一个勾选是否生成Dao实现类的功能

### ISSUE THREAD

**Issue by g-wangtao** [zouzg/mybatis-generator-gui#152]
希望可以有一个勾选是否生成Dao实现类的功能

**Comment by zouzg** [comment]
你是指不生成Example类吗？

**Comment by g-wangtao** [comment]
项目中Dao的实现层都是由Mybatis自动实现的，但是有时候会有多数据源的情况，比如需要取Redis缓存的时候，这个时候如果能生成Dao的实现层由自己控制数据源的话就会方便很多。

**Comment by zouzg** [comment]
不是很明白你的意思，你是指mybatis的配置Java类吗？

**Comment by g-wangtao** [comment]
作者的这个程序写的已经很好了，用现在的开发方式是直接写Mapper接口由mybatis代理实现也是常用的做法，但是有时候需要的数据是从Redis中获取或者需要对数据进行其他处理的时候Mapper代理的方式就无能为力了，只能把原本数据层代码放到业务层中了，如果这个时候能有Mapper的实现层也就是Dao层的话就会方便很多。关于Mapper代理和原始dao层我可能描述的不是很清楚，作者可以查看这篇博文：https://www.jianshu.com/p/7f13c4b9f0c0?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation

**Comment by zouzg** [comment]
通常DAO由开发人员自己编写，位于Mapper层之上。DAO层封装Mapper层的参数转换，对外暴露Model级的增删改查。建议参考我的这个类。
![image](https://user-images.githubusercontent.com/3505708/37754021-b94e5218-2dda-11e8-87d2-60958faddd43.png)
