### ISSUE TITLE
这个工具很好, 是否可以提示更加明确一些?

### ISSUE THREAD

**Issue by objectboy2016** [zouzg/mybatis-generator-gui#153]

**Comment by zouzg** [comment]
提示方面的确做的不是很好，后面可以优化一下。

**Comment by objectboy2016** [comment]
嗯嗯,  生成实体类如果可以的话可以添加直接和数据库名一致的按钮,,,   因为有些人可能喜欢这样 ,比如在下...哈哈

**Comment by zouzg** [comment]
新版本增加了部分tooltip，对于比较难懂的选项，把光标放在输入框中会有提示。
