### ISSUE TITLE
为什么我生成的Mapper.xml文件里边数据库和表中间是两个.

### ISSUE THREAD

**Issue by lzwling** [zouzg/mybatis-generator-gui#154]
<select id="selectByPrimaryKey" parameterType="java.lang.Integer" resultMap="BaseResultMap">
    select 
    <include refid="Base_Column_List" />
       from spring..account
    where id = #{id,jdbcType=INTEGER}
  </select>

上边spring是数据库名，account是表名，from后边会有个表名关键还是两个..；请问该怎么去解决这个问题

**Comment by lzwling** [comment]
![tim 20180120134652](https://user-images.githubusercontent.com/28377569/35180329-d87f56c2-fde8-11e7-9e46-45687fbb9e3f.png)
![image](https://user-images.githubusercontent.com/28377569/35180333-f2e23da4-fde8-11e7-9b0c-9dca3d918c4a.png)
像上边红线下边为什么会有数据库名和两个点，是不是我使用的不太对

**Comment by alynlin** [comment]
![image](https://user-images.githubusercontent.com/5954969/35320854-398a4834-0120-11e8-9fff-f920c9f685d1.png)

**Comment by lzwling** [comment]
不错，可以了

**Comment by cjp314** [comment]
这还得改代码啊

**Comment by zsw12013** [comment]
是的  我这边也提示这个了 mysql

**Comment by lkp123456** [comment]
com.zzg.mybatis.generator.bridge.MybatisGeneratorBridge类

72行：tableConfig.setSchema(selectedDatabaseConfig.getSchema());

**Comment by zouzg** [comment]
这个是mybatis-generator-core的bug，可以查看：https://github.com/mybatis/generator/issues/334
不过MySQL通过特殊判断解决了，感谢各位的意义。
另外抱歉最新忙一直没有关注项目，此问题已经解决。
