### ISSUE TITLE
maven编译错误

### ISSUE THREAD

**Issue by retuenepz** [zouzg/mybatis-generator-gui#155]
我clone后尝试用IDEA去运行它，maven编译无法通过，大量的找不到符号错误，请问是什么原因呢。部分错误如下：
 ` 符号:   类 Alert`
 ` 位置: 类 com.zzg.mybatis.generator.view.AlertUtil`
`[ERROR] /D:/IDEA_WORKSPACE/mybatis-generator-ui/mybatis-generator gui/src/main/java/com/zzg/mybatis/generator/view/AlertUtil.java:[23,38] 程序包Alert不存在`
`[ERROR] /D:/IDEA_WORKSPACE/mybatis-generator-ui/mybatis-generator-gui/src/main/java/com/zzg/mybatis/generator/view/AlertUtil.java:[35,9] 找不到符号`

**Comment by zouzg** [comment]
请作用java 1.8.0_40以上版本的java
