### ISSUE TITLE
mvn jfx:jar 时报错:程序包Alert不存在

### ISSUE THREAD

**Issue by shiyunlai** [zouzg/mybatis-generator-gui#156]
错误：
[ERROR] /Users/megapro/Develop/mybatis/mybatis-generator-gui/src/main/java/com/zzg/mybatis/generator/view/AlertUtil.java:[35,27] 找不到符号
[ERROR] 符号:   类 Alert
[ERROR] 位置: 类 com.zzg.mybatis.generator.view.AlertUtil
[ERROR] /Users/megapro/Develop/mybatis/mybatis-generator-gui/src/main/java/com/zzg/mybatis/generator/view/AlertUtil.java:[35,38] 程序包Alert不存在
...
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mybatis-generator-gui: Compilation failure
...
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
...

环境：
MacOS 
java version "1.8.0_20"

**Comment by zouzg** [comment]
java 1.8.0_40以上版本，请看首页的描述。
