### ISSUE TITLE
xml中生成的sql中，表明错误。

### ISSUE THREAD

**Issue by wangzhiziqiao** [zouzg/mybatis-generator-gui#161]
现在生成的xml的sql是  “select * from 数据库名..表明” 这种格式的。出错的原因是MybatisGeneratorBridge.java 类的  72行代码赋值错误应该修改为

tableConfig.setSchema(selectedDatabaseConfig.getSchema());

**Comment by zouzg** [comment]
已经更新，抱歉一直有事没有关注项目。

**Comment by AconHu** [comment]
爲什麽還是不行啊，我這個還是庫名跟表明中間是兩個點呢
