### ISSUE TITLE
jdk-9.0.1 无法使用

### ISSUE THREAD

**Issue by hisheng** [zouzg/mybatis-generator-gui#162]
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.8.3:jar (default-cli) on project mybatis-generator-gui: Exe                                     cution default-cli of goal com.zenjava:javafx-maven-plugin:8.8.3:jar failed: Plugin com.zenjava:javafx-maven-plugin:8.8.3 or                                      one of its dependencies could not be resolved: Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at spec                                     ified path C:\Program Files\Java\jdk-9.0.1/../lib/ant-javafx.jar -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by chenbuer** [comment]
[#141](https://github.com/zouzg/mybatis-generator-gui/issues/141)
> 这里面说了

**Comment by zouzg** [comment]
jdk1.9 暂时不支持
