### ISSUE TITLE
生成sql，数据库.表名，多出一个.变成 数据库..表名

### ISSUE THREAD

**Issue by abincai** [zouzg/mybatis-generator-gui#164]
如题目

**Comment by SBLiuEason** [comment]
这个是另一个项目的bug，在mybatis-generator-core这个项目里，StringUtility.java里两次为空判断后，又加了一个Seperator “.”，要开issue要去另一个项目开。不过我已经提交了，目前没有closed，建议你自己下载源码重新修改java文件再编译成class应付应付先。

**Comment by zouzg** [comment]
@abincai 抱歉最新一直很忙，没有关注项目。
如SBLiuEason如，的确是mybatis-generator-core的问题，目前最新代码通过其他方式已经解决，麻烦更新一下。

**Comment by zouzg** [comment]
已经解决，抱歉最近忙没有关注项目.
