### ISSUE TITLE
工具如何 去掉Mybatis Generator生成的一堆 example

### ISSUE THREAD

**Issue by GuodongY** [zouzg/mybatis-generator-gui#17]
mybatis generator自动生成的代码里老是有一堆example，虽然说他封装的东西比较多，但是大部分时候并不会用到。如果需要改的时候，在接口和mapper里修改便是了。

配置的方法如下：

<table schema="general" tableName="tb_table_name" domainObjectName="EntityName"
    enableCountByExample="false" enableUpdateByExample="false" enableDeleteByExample="false"
    enableSelectByExample="false" selectByExampleQueryId="false" >
    <property name="useActualColumnNames" value="true"/>
</table>
 

请问你这个工具如何去掉？？？

**Comment by astarring** [comment]
为什么要去掉呢，多生成一点不是更好的吗。

**Comment by rbsrcy** [comment]
@GuodongY 
You can modify the method in the source file  "com.zzg.mybatis.generator.bridge.MybatisGeneratorBridge" name generate()

add flowing code after line 63

`
        tableConfig.setCountByExampleStatementEnabled(false);
        tableConfig.setDeleteByExampleStatementEnabled(false);
        tableConfig.setSelectByExampleStatementEnabled(false);
        tableConfig.setUpdateByExampleStatementEnabled(false);
`

**Comment by fireworkDks** [comment]
@rbsrcy 非常感谢!Thank you so much!

**Comment by fireworkDks** [comment]
灰常感谢楼主分享的这个工具!!感觉挺好用的!!
另外,有些时候我们确实不需要那些example,比如我昨天帮别人添加个小功能,只是做一个简单的记录信息!只用到增查改三个最简单的操作!
不过用楼上的已经解决!!

**Comment by astarring** [comment]
@fireworkDks 既然大家觉得有这个需求，那我在下一个版本加入这个配置用户可以选择生成哪些代码。

**Comment by fireworkDks** [comment]
@astarring 期待大神的下个版本!

**Comment by Fancyiscrying** [comment]
good

**Comment by zouzg** [comment]
新版直接不勾选生成Example即可
