### ISSUE TITLE
OMG, if I run the generate twice,I get duplicate configure in same xml?

### ISSUE THREAD

**Issue by tain198127** [zouzg/mybatis-generator-gui#172]
If I run the generate twice,I get **DUPLICATE** configure in same xml
After my check, last I found duplicate configuration in my mapper.xml;
Shall we have some promotion or toast? Or avoid that?

**Comment by zouzg** [comment]
This issue have resolved in the lastest master branch(version 0.8.5). I provided a checkbox let use choose whether override old XML file, it yes, it will delete old XML file and generate a new one.

**Comment by zouzg** [comment]
@tain198127
