### ISSUE TITLE
生成的映射文件 所有的sql都生成两次

### ISSUE THREAD

**Issue by xihuanyigeren** [zouzg/mybatis-generator-gui#181]

**Comment by xihuanyigeren** [comment]
![b867b74e-8c79-4655-84e7-ecb4a5b300d7](https://user-images.githubusercontent.com/38148657/39123397-5794f400-472a-11e8-9205-7276805d200d.png)

**Comment by hhlaohu** [comment]
因为你点了两次生成，映射文件不会覆盖原来的，只会在下面新增，mybatis-generator的老BUG了，暂时没解决

**Comment by hhlaohu** [comment]
重新生成时，建议删除原来的映射文件

**Comment by zouzg** [comment]
已解决
