### ISSUE TITLE
BUG反馈：在java.version为1.8.0_152-ea时无法运行

### ISSUE THREAD

**Issue by wusir** [zouzg/mybatis-generator-gui#185]
java -version：
java version "1.8.0_152-ea"
Java(TM) SE Runtime Environment (build 1.8.0_152-ea-b04)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b04, mixed mode)

在MainUI.java的40行位置，解析会失败。

**Comment by zouzg** [comment]
了解，已更新。不过请尽是使用正式版本，你这个是early access版本。
