### ISSUE TITLE
判断jdk版本的代码有问题应该改进

### ISSUE THREAD

**Issue by lerry903** [zouzg/mybatis-generator-gui#191]
MainUI.java这个类中判断jdk版本的代码应该优化，目前对jdk10校验会有问题。
可以将获取到的数据用.分割成数组在比较。
public static void main(String[] args) {
		String version = System.getProperty("java.version");
		if (Integer.parseInt(version.substring(0,1)) == 1 && Integer.parseInt(version.substring(2, 3)) >= 8 && Integer.parseInt(version.substring(6)) >= 60 || Integer.parseInt(version.substring(0,1))>=9) {
			launch(args);
		}else {
			JFrame jFrame = new JFrame("版本错误");
			jFrame.setSize(500, 100);
			jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			JPanel jPanel = new JPanel();
			JLabel jLabel = new JLabel("JDK的版本不能低于1.8.0.60，请升级至最近的JDK 1.8再运行此软件，当前版本:" + version);
			jPanel.add(jLabel);
			jFrame.add(jPanel);
			jFrame.setLocationRelativeTo(null);
			jFrame.setVisible(true);

		}
	}

**Comment by zouzg** [comment]
已删除此段代码
