### ISSUE TITLE
打开连接后显示的表名没有进行排序，难于检索

### ISSUE THREAD

**Issue by cyclamenkde** [zouzg/mybatis-generator-gui#205]
建议先增加排序功能，如： DbType为SQL_Server时，按name排序
mybatis-generator-gui-master\src\main\java\com\zzg\mybatis\generator\util\DbUtil.java 文件中
String sql = "select name from sysobjects  where xtype='u' or xtype='v' order by name";

**Comment by zouzg** [comment]
已增加，多谢贡献。
