### ISSUE TITLE
连接mysql后 双击无反应

### ISSUE THREAD

**Issue by TAMCHINGLOL** [zouzg/mybatis-generator-gui#206]
![image](https://user-images.githubusercontent.com/18702813/44075345-153f3fd6-9fcf-11e8-8de5-dc5d88f52ce3.png)

启动环境：
Windows7+IDEA+JDK1.8.0.91
![image](https://user-images.githubusercontent.com/18702813/44075384-32eb8d82-9fcf-11e8-9715-b6a16705f070.png)

**Comment by zouzg** [comment]
请使用最新版本，现在应该OK了
