### ISSUE TITLE
关于数据库decimal 类型字段的映射

### ISSUE THREAD

**Issue by pencilso** [zouzg/mybatis-generator-gui#212]
decimal 类型映射到Java里面 竟然是Long
不应是BigDecimal 吗？
而且 定制列  根本没用啊？ 我改了Java type后 生成的还是Long类型。
![qq 20180906112930](https://user-images.githubusercontent.com/16483654/45133507-24932a00-b1c8-11e8-8ad8-6c10c665449a.jpg)

**Comment by liangxiao0315** [comment]
确实有这个问题

**Comment by zouzg** [comment]
我测试下来的OK的，请提供你的数据库类型

**Comment by zouzg** [comment]
JavaType你输入文字后需要按Enter保存，然后再点确认，才可生效，我的上面提示信息已经更新

**Comment by chenkuan233** [comment]
decimal(13,0)如果是这种小数位为0的生成实体会变成Long，其他有小数的是正常的，望改进（mysql）

**Comment by chenkuan233** [comment]
> JavaType你输入文字后需要按Enter保存，然后再点确认，才可生效，我的上面提示信息已经更新

decimal(13,0)如果是这种小数位为0的生成实体会变成Long，其他有小数的是正常的，望改进（mysql）

**Comment by chenkuan233** [comment]
> 我测试下来的OK的，请提供你的数据库类型

decimal(13,0)如果是这种小数位为0的生成实体会变成Long，其他有小数的是正常的，望改进（mysql）
