### ISSUE TITLE
我的mapper.xml里怎么没有生成select语句

### ISSUE THREAD

**Issue by steven945** [zouzg/mybatis-generator-gui#224]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.steven.ssm.dao.NewsDao">
  <resultMap id="BaseResultMap" type="com.steven.ssm.entity.News">
    <result column="id" jdbcType="INTEGER" property="id" />
    <result column="title" jdbcType="VARCHAR" property="title" />
    <result column="content" jdbcType="VARCHAR" property="content" />
    <result column="create_date" jdbcType="TIMESTAMP" property="createDate" />
    <result column="photo" jdbcType="VARCHAR" property="photo" />
  </resultMap>
  <insert id="insert" parameterType="com.steven.ssm.entity.News">
    insert into news (id, title, content, 
      create_date, photo)
    values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, 
      #{createDate,jdbcType=TIMESTAMP}, #{photo,jdbcType=VARCHAR})
  </insert>
  <insert id="insertSelective" parameterType="com.steven.ssm.entity.News">
    insert into news
    <trim prefix="(" suffix=")" suffixOverrides=",">
      <if test="id != null">
        id,
      </if>
      <if test="title != null">
        title,
      </if>
      <if test="content != null">
        content,
      </if>
      <if test="createDate != null">
        create_date,
      </if>
      <if test="photo != null">
        photo,
      </if>
    </trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
      <if test="id != null">
        #{id,jdbcType=INTEGER},
      </if>
      <if test="title != null">
        #{title,jdbcType=VARCHAR},
      </if>
      <if test="content != null">
        #{content,jdbcType=VARCHAR},
      </if>
      <if test="createDate != null">
        #{createDate,jdbcType=TIMESTAMP},
      </if>
      <if test="photo != null">
        #{photo,jdbcType=VARCHAR},
      </if>
    </trim>
  </insert>
</mapper>

**Comment by zouzg** [comment]
请把完整的xml文件附上
