### ISSUE TITLE
关于连接Oracle  sid和服务名 的问题解决方案.

### ISSUE THREAD

**Issue by gghqq** [zouzg/mybatis-generator-gui#225]
![_20181118191843](https://user-images.githubusercontent.com/36395673/48671676-ec647c00-eb66-11e8-9368-deaa10af4e09.png)
 
将model下面DBtype 的  ORACLE  修改如下即可
"jdbc:oracle:thin:@//%s:%s/%s"

**Comment by zouzg** [comment]
多谢，已加入最新代码中。
