### ISSUE TITLE
建议修改的功能

### ISSUE THREAD

**Issue by yan-qiang** [zouzg/mybatis-generator-gui#261]
建议：
1.覆盖之前的文件的时候，只覆盖自动生成的部分，自己手写的部分不覆盖，比如：自己在xml里加了一个复杂的sql，后来数据库表新增了字段，需要从新生成，覆盖之后就没有了
2.生成哪些接口可以让用户自己选择，比如：我只想生成一个insertSelective，不想生成insert，只需要勾选一下就可以

**Comment by chuntungho** [comment]
idea搜索Mybatis Builder, 支持自动合并

**Comment by zouzg** [comment]
> 建议：
> 1.覆盖之前的文件的时候，只覆盖自动生成的部分，自己手写的部分不覆盖，比如：自己在xml里加了一个复杂的sql，后来数据库表新增了字段，需要从新生成，覆盖之后就没有了
> 2.生成哪些接口可以让用户自己选择，比如：我只想生成一个insertSelective，不想生成insert，只需要勾选一下就可以

#1 没法只覆盖生产部分，用户有可能写在文件末尾，有可能写在中间，比较容易覆盖出错，建议还是自己使用IDE覆盖前提交一下，然后merge。
