### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by xiaoer66** [zouzg/mybatis-generator-gui#266]
针对小白可以顺便在文章开头写上这个工具的搭建方式 哈哈

**Comment by chuntungho** [comment]
IDEA环境可以安装图形插件Mybatis Builder，https://chuntung.com/mybatis-builder/

**Comment by xiaoer66** [comment]
蟹蟹


| |
vik张
|
|
vik666@126.com
|
签名由网易邮箱大师定制
在2019年5月24日 18:02，Tony Ho<notifications@github.com> 写道：

IDEA环境可以安装图形插件Mybatis Builder，https://chuntung.com/mybatis-builder/

**Comment by zouzg** [comment]
可以的，后续会上一个视频可以介绍如何使用。
