### ISSUE TITLE
希望可以根据表名查找表

### ISSUE THREAD

**Issue by shuaige112500** [zouzg/mybatis-generator-gui#283]
工具很好用，有以下几点可以完善
1. 目前选择表不带检索功能，当表很多时还需要手动查找，不太方便
2. 希望可以将数据库中column的注释生成到Entity里面，我是SQL Server，当前没有生成
3. 希望可以加个选项，可以选择只生成entity, 或者只生成mapper

**Comment by slankka** [comment]
@shuaige112500 
1. 已经支持。clone之后编译即可。

**Comment by zouzg** [comment]
已经支持

**Comment by zouzg** [comment]
#3 我调研一下
