### ISSUE TITLE
启动连接失败

### ISSUE THREAD

**Issue by 1ghosts** [zouzg/mybatis-generator-gui#304]
导入后启动提示缺少5.1.38的mysql-connector-java
添加启动失败
 发现本地安装mysql是8.0.x版本，需要配置配置8.0.x的mysql-connector-java，就可以正常使用:flushed::flushed::flushed::flushed:

**Comment by zmr518** [comment]
也报这个错，看日志是加载jar包的路径有问题，你是怎么配置8.0.x的

**Comment by zmr518** [comment]
如果mysql是8.0.x的版本，在数据库连接界面数据库类型中MYSQL_8就解决了

**Comment by Iverlei** [comment]
同样的问题，找不到mysql-connect-java-8.0.x驱动

**Comment by zouzg** [comment]
再次测试有了一下，选择MySQL8是可以的。

**Comment by WeiXiLong** [comment]
我本地安装版本是5.6.47，也是这个错误
