### ISSUE TITLE
考虑增加一下屏蔽example类生成的功能

### ISSUE THREAD

**Issue by coolphk** [zouzg/mybatis-generator-gui#31]
考虑增加一下屏蔽example类生成的功能

**Comment by fireworkDks** [comment]
这个之前大伙提过了~~作者也证实下个版本会有该功能!大家一起期待吧~

**Comment by fireworkDks** [comment]
@coolphk 
或者自己手动处理下
找到类:"com.zzg.mybatis.generator.bridge.**MybatisGeneratorBridge**"
63行添加如下代码:

tableConfig.setCountByExampleStatementEnabled(false); tableConfig.setDeleteByExampleStatementEnabled(false); tableConfig.setSelectByExampleStatementEnabled(false); tableConfig.setUpdateByExampleStatementEnabled(false);

**Comment by zouzg** [comment]
新版不勾选"使用Example"即可
